While executing file `Games/Saving/saving.py` an error occurred (<module> refers to the game file):

Traceback (most recent call last):
  File "launcher.py", line 307, in <module>
  File "saving.py", line 20, in <module>
RuntimeError: EngineSave: ERROR: Could not load entry! Type unknown!
